version: "3.7"
services:

  php-fpm:
    container_name: news-feed-php-fpm
    build:
      context: ./docker
      dockerfile: php.Dockerfile
      target: php_fpm
    ports:
      - '9006:9000'
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/.env.dev.docker:/var/www/.env
    networks:
      - news-feed-network

  nginx:
    build:
      context: ./docker
      dockerfile: nginx.Dockerfile
    container_name: news-feed-nginx
    ports:
      - 8700:80
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www
      - ./docker/_vhost/000-default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/_config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - news-feed-network

  mysql:
    image: mariadb:jammy
    container_name: news-feed-mysql
    environment:
      - PMA_ARBITRARY=1
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=news_feed
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    networks:
      - news-feed-network

  phpmyadmin:
    image: phpmyadmin
    container_name: news-feed-phpmyadmin
    ports:
      - 8780:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=admin
      - PMA_PASSWORD=admin
    networks:
      - news-feed-network

networks:
  news-feed-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
